### PR TITLE
Add ban icon

### PR DESCRIPTION
**Pull request by basham**
Part of the work for #29.

Ban icon

Notes:

1. I sorted the Illustrator art boards alphabetically.
2. I angled the slash in the icon south-east, to follow the same direction as the `audio-off` icon, although it's pretty [50/50 on agreement about the direction](https://thenounproject.com/search/?q=ban).

### CODE REVIEW

**Comment by basham** [comment]
Please review, @levimcg.

**Comment by basham** [comment]
The demo site is not updated with the new `ban` icon. I'm guessing you changed some repo settings in prep for your #33 PR?

**Comment by levimcg** [comment]
Nope, I haven't changed it yet. It only deploys the demo site from the `docs` folder on `master`. I'll merge it in real quick and then it should update the demo.

**Comment by levimcg** [comment]
There we go. It is updated now. https://indiana-university.github.io/rivet-icons/

**Pull request merged**
