### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by basham**
I'd like to release a patch update (v1.0.3) that upgrades all the dependencies of this project. Notes:

1. I've noticed a similar [security warning to this one](https://github.com/indiana-university/rivet-icons/security/dependabot/26) in other projects. That is a result of `svg-sprite`. I've updated it to the new `v2.0.0` released a few weeks ago. I don't know if it will resolve it, but it is our best chance to do so.
2. The changes in `svg-sprite` means that it minified the symbols in `rivet-icons.html`, `rivet-icons.js`, and `rivet-icons.svg` slightly differently. However, I'm not noticing any visual regressions in the docs site that I served locally.
3. The icons continue to work and look identically in the latest Chrome, Firefox, and Safari.
4. I upgraded `gh-pages`. It claims that there are [no breaking changes in this new `4.0.0` release](https://github.com/tschaub/gh-pages/releases/tag/v4.0.0). I have not tested this, but I'm sure it will be fine.
5. There were some changes I needed to make in `build.js` to accommodate depreciation warnings in Node 16.
6. All dependencies in `package-lock.json` are resolved through the public npm registry, instead of the IU Nexus one. That makes it friendlier, as those who try to run this repo will no longer need any special authentication.

### CODE REVIEW

**Review by levimcg — APPROVED** [review]
Nice, thank you for taking care of this!

**Comment by basham** [comment]
Excellent. Could you take care of publishing this update? Want me to merge it, or will you do that?

**Comment by levimcg** [comment]
I can go ahead and merge it and publish the update. I've got to run out for the day here in about five, but I can do it first thing Monday if that's cool?

**Comment by basham** [comment]
Yep, good for me. No rush. Thanks!

**Pull request merged**
