### PR TITLE
Espd icons

### PR DESCRIPTION
**Pull request by thrclark**
Contributing 10 new icons that we've created to use in our team projects:

- circle
- circle-solid
- data
- image
- ordered-list
- link
- sidebyside
- heart
- heart-solid
- expand

Icon preview available [here](https://espd.sitehost.iu.edu/rvb/develop/php/lib-extra-icons.php)

On a side note, IU Mobile and the new One.IU design use different heart icon designs.  I was asked to submit the ESPD heart icon design so we can work towards having only one as the standard.

### CODE REVIEW

**Comment by jwbennet** [comment]
Checking in here. We're about to start implementing new screens for One.IU which will use some of these icons. If we think these will need to be altered it would help to get that feedback soon.

**Comment by levimcg** [comment]
Hey, @thrclark & @jwbennet 

I apologize for the delay. The only thing I'm seeing there that will need to change is some tweaks to the bottom shape of the heart icons. Right now it's has some curve and sharpness to it that don't match the rest of the icon set. As example if you look at the "Map pin" icon which has similar shape at the bottom where the two lines intersect, it is much more of a rounded intersection of the two lines that are straighter/simpler and match the simplified/graphic aesthetic as the rest of the set.

See pin example close up:
Screen Shot 2021-03-04 at 11 24 27 AM

They're such similar shapes, so it makes sense that the heart should be drawn this way as well. Since it's taken us so long to get back with you all on this PR, I'm fine to go ahead and merge this stuff in now, and then I can touch up the heart logo to make it better match the rest of the icons as a part of the release process that would include all these new icons.

I can commit to having the `0.5.0` release done by end of day Monday 03/08/21. **Does that sound agreeable to you both?**

Thanks again for your patience. 🙌🏻

**Comment by levimcg** [comment]
@thrclark @jwbennet Just wanted to follow up really quick on this. `0.5.0` has been released with these new icons including an updated heart icon. See #69 and #70 for more info.

https://github.com/indiana-university/rivet-icons/releases/tag/v0.5.0

**Comment by jwbennet** [comment]
Awesome, thank you for your assistance!

**Pull request merged**
